name: Build

on:
  push:
    branches:
      - full-recode
      - main
  pull_request:
    branches:
      - full-recode
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system packages needed for headless gl
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          build-essential
          libgl1-mesa-dri
          libglapi-mesa
          libglew-dev
          libglu1-mesa-dev
          libosmesa6
          libxi-dev
          mesa-utils
          pkg-config

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install project dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
