name: Tests + SonarCloud

on:
  push:
    branches:
      - full-recode
      - main
  pull_request:
    branches:
      - full-recode
      - main

jobs:
  tests:
    name: Tests + SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system packages needed for headless gl
        run: >-
          sudo apt-get install -y
          build-essential
          libgl1-mesa-dri
          libglapi-mesa
          libglew-dev
          libglu1-mesa-dev
          libosmesa6
          libxi-dev
          mesa-utils
          pkg-config

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install project dependencies
        run: npm ci
      - name: Run the tests
        run: xvfb-run npm run test:ci

      - name: Run SonarCloud analysis
        if: '!cancelled()'
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=spraxdev
            -Dsonar.projectKey=SpraxDev_Api.Sprax2013.de
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.typescript.tsconfigPaths=tsconfig.json
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.sources=src/
            -Dsonar.tests=tests/
            -Dsonar.test.inclusions=tests/**/*.test.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
